[package]
name = "mµdle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "2.5.0"
scraper = "0.13.0"
serde_json = "1.0.85"
log = "0.4.17"